<?php $this->partial('layouts/header'); ?>
<div class="container">

   <p>Liste des composants</p>
    <table class="table">
        <thead>
        <tr>
            <th>ID</th>
            <th>Type</th>
            <th>Charge</th>
            <th>Progression</th>
            <th>Désignation</th>
            <th>ID Module</th>
        </tr>
        </thead>
        <tbody>
        <?php if (!empty($composants)) {
            foreach ($composants as $composant) { ?>
                <tr>
                    <td><?php echo $composant->id; ?></td>
                    <td><?php echo $composant->type; ?></td>
                    <td><?php echo $composant->charge; ?></td>
                    <td><?php echo $composant->progression; ?></td>
                    <td><?php echo $composant->libelle; ?></td>
                    <td><?php echo $composant->id_module; ?></td>
                </tr>
            <?php }
        } else { ?>
            <tr>
                <td colspan="3">Aucun chef de projet trouvé.</td>
            </tr>
        <?php } ?>
        </tbody>
    </table>
</div>

