<?php $this->partial('partials/header'); ?>
<div class="container">

   <p>Liste des composants</p>
    <table class="table">
        <thead>
        <tr>
            <th>Type</th>
            <th>Charge</th>
            <th>Progression</th>
            <th>Désignation</th>
            <th>Module</th>
        </tr>
        </thead>
        <tbody>
        <?php if (!empty($composants)) {
            foreach ($composants as $composant) { ?>
                <tr>

                    <td><?php echo $composant->getTypeLibelle(); ?></td>
                    <td><?php echo $composant->getCharge(); ?></td>
                    <td><?php echo $composant->getProgression(); ?></td>
                    <td><?php echo $composant->getLibelle(); ?></td>
                    <td> <?php echo $composant->getLibelleModule(); ?></td>
                </tr>
            <?php }
        } else { ?>
            <tr>
                <td colspan="3">Aucun chef de projet trouvé.</td>
            </tr>
        <?php } ?>
        </tbody>
    </table>
</div>

