<?php $this->partial('partials/header'); ?>
<div class="container">
    <h2>Créer un nouveau collaborateur</h2>
    <form action="<?= $this->url->get('themys/collaborateur/create') ?>" method="post">
        <div class="form-group">
            <label for="nom">Nom:</label>
            <input type="text" class="form-control" id="nom" name="nom" >
        </div>
        <div class="form-group">
            <label for="prenom">Prénom:</label>
            <input type="text" class="form-control" id="prenom" name="prenom" >
        </div>
        <div class="form-group">
            <label for="prime_embauche">Prime d'embauche:</label>
            <input type="number" class="form-control" id="prime_embauche" min="5000" max="50000" name="prime_embauche" value="5000þ">
        </div>
        <div class="form-group">
            <div class="form-group">
                <label for="niveau_competence">Niveau compétence:</label>
                <select name="niveau_competence" class="form-control">
                    <?php foreach ($this->view->niveauCompetence as $row) {
                        echo '<option value="'.$row['id'].'">'.$row['libelle'].'</option>';
                    } ?>
                </select>
            </div>
        </div>
        <input type="submit" class="btn btn-primary"  value="Creer"/>
    </form>
</div>
