<?php $this->partial('partials/header'); ?>
<div class="container">
    <div class="mt-3 mb-3">
        <button type="submit" class="btn btn-primary" onclick="redirect()">Créer un collaborateur</button>
    </div>



   <p>Liste des collaborateurs</p>
    <table class="table">
        <thead>
        <tr>
            <th>ID</th>
            <th>Nom</th>
            <th>Prénom</th>
            <th>Prime d'embauche</th>
            <th>Niveau compétence</th>
        </tr>
        </thead>
        <tbody>
        <?php
        if (!empty($collaborateurs)) {
            foreach ($this->view->collaborateurs as $row): ?>
                <tr>
                    <td><?php echo $row['id']; ?></td>
                    <td><?php echo $row['nom']; ?></td>
                    <td><?php echo $row['prenom']; ?></td>
                    <td><?php echo $row['primeEmbauche']; ?></td>
                    <td><?php echo $row['niveauCompetence']; ?></td>
                </tr>
            <?php endforeach;
        } ?>
        </tbody>
    </table>
</div>

<script>
    function redirect() {
        // Replace 'collaborateur/index' with the desired route for the redirection
        window.location.href = '<?= $this->url->get('themys/collaborateur/create') ?>';
    }
</script>

