<?php $this->partial('partials/header'); ?>
<div class="container">

   <p>Liste des projets</p>
    <table class="table">
        <thead>
        <tr>
            <th>ID</th>
            <th>Libellé</th>
            <th>Prix</th>
            <th>Statut</th>
            <th>Application</th>
            <th>Chef de projet</th>
        </tr>
        </thead>
        <tbody>
        <?php
        if (!empty($projets)) {
            foreach ($projets as $row): ?>
                <tr>
                    <td><?php echo $row['id']; ?></td>
                    <td><?php echo $row['libelle']; ?></td>
                    <td><?php echo $row['prix']; ?></td>
                    <td><?php echo $row['status']; ?></td>
                    <td><?php echo $row['idApplication']; ?></td>
                    <td><?php echo $row['idChefDeProjet']; ?></td>
                </tr>
            <?php endforeach;
        } ?>
        </tbody>
    </table>
</div>

