<?php $this->partial('partials/header'); ?>
<div class="container">

   <p>Liste des clients</p>
    <table class="table">
        <thead>
        <tr>
            <th>Type</th>
            <th>Ridet</th>
            <th>Raison sociale</th>
        </tr>
        </thead>
        <tbody>
          <?php if (!empty($clients)) {
              foreach ($clients as $row): ?>
              <tr>
                  <td><?php echo $row['ss2i']; ?></td>
                  <td><?php echo $row['ridet']; ?></td>
                  <td><?php echo $row['raison_sociale']; ?></td>
              </tr>
              <?php endforeach;
          } ?>
        </tbody>
    </table>
</div>

