<?php $this->partial('partials/header'); ?>
<div class="container">

   <p>Liste des clients</p>
    <table class="table">
        <thead>
        <tr>
            <th>Type</th>
            <th>Ridet</th>
            <th>Raison sociale</th>
        </tr>
        </thead>
        <tbody>
        <?php if (!empty($clients)) {
            foreach ($clients as $client) { ?>
                <tr>
                    <td><?php echo $client->ss2i ; ?></td>
                    <td><?php echo $client->ridet; ?></td>
                    <td><?php echo $client->raison_sociale; ?></td>
                </tr>
            <?php }
        } else { ?>
            <tr>
                <td colspan="3">Aucun client trouvé.</td>
            </tr>
        <?php } ?>
        </tbody>
    </table>
</div>

