<?php $this->partial('partials/header'); ?>
<div class="container">

   <p>Liste des équipes</p>
    <table class="table">
        <thead>
        <tr>
            <th>ID</th>
            <th>Equipe</th>
            <th>Chef de projets</th>
        </tr>
        </thead>
        <tbody>
        <?php
        if (!empty($equipes)) {
            foreach ($equipes as $row): ?>
                <tr>
                    <td><?php echo $row['id']; ?></td>
                    <td><?php echo $row['libelleEquipe']; ?></td>
                    <td><?php echo $row['idChefDeProjet']; ?></td>
                </tr>
            <?php endforeach;
        } ?>
        </tbody>
    </table>
</div>

