<?php $this->partial('partials/header'); ?>
<div class="container">

   <p>Liste des applications</p>
    <table class="table">
        <thead>
        <tr>
            <th>ID</th>
            <th>Compétence</th>
            <th>Indice de production</th>
            <th>ID Equipe</th>
            <th>ID Collaborateur</th>
        </tr>
        </thead>
        <tbody>
        <?php
        if (!empty($developpeurs)) {
            foreach ($developpeurs as $row): ?>
                <tr>
                    <td><?php echo $row['id']; ?></td>
                    <td><?php echo $row['competence']; ?></td>
                    <td><?php echo $row['indiceProduction']; ?></td>
                    <td><?php echo $row['idEquipe']; ?></td>
                    <td><?php echo $row['idCollaborateur']; ?></td>
                </tr>
            <?php endforeach;
        } ?>
        </tbody>
    </table>
</div>

