<?php $this->partial('partials/header'); ?>
<div class="container">
    <div class="mt-3 mb-3">
        <button type="submit" class="btn btn-primary" onclick="redirect()">Créer un developpeur</button>
    </div>

   <p>Liste des developpeurs</p>
    <table class="table">
        <thead>
        <tr>
            <th>ID</th>
            <th>Compétence</th>
            <th>Indice de production</th>
            <th>ID Equipe</th>
            <th>ID Collaborateur</th>
            <th>Actions</th>
        </tr>
        </thead>
        <tbody>
        <?php
        if (!empty($developpeurs)) {
            foreach ($developpeurs as $row): ?>
                <tr>
                    <td><?php echo $row['id']; ?></td>
                    <td><?php echo $row['competence']; ?></td>
                    <td><?php echo $row['indiceProduction']; ?></td>
                    <td><?php echo $row['idEquipe']; ?></td>
                    <td><?php echo $row['idCollaborateur']; ?></td>
                    <td>
                        <button class="btn btn-danger" onclick="window.location.href='<?= $this->url->get('themys/developpeur/delete/'.$row['id']) ?>'">
                            Supprimer
                        </button>
                    </td>
                </tr>
            <?php endforeach;
        } ?>
        </tbody>
    </table>
</div>

<script>
    function redirect() {
        // Replace 'developpeur/index' with the desired route for the redirection
        window.location.href = '<?= $this->url->get('themys/developpeur/create') ?>';
    }
</script>
