<?php $this->partial('layouts/header'); ?>
<div class="container">

   <p>Liste des modules</p>
    <table class="table">
        <thead>
        <tr>
            <th>ID</th>
            <th>Libellé</th>

        </tr>
        </thead>
        <tbody>
        <?php if (!empty($modules)) {
            foreach ($modules as $module) { ?>
                <tr>
                    <td><?php echo $module->id; ?></td>
                    <td><?php echo $module->libelle; ?></td>

                </tr>
            <?php }
        } else { ?>
            <tr>
                <td colspan="3">Aucun module trouvé.</td>
            </tr>
        <?php } ?>
        </tbody>
    </table>
</div>

